### ISSUE TITLE
Roadmap #1

### ISSUE THREAD

**Issue by JadeMaveric** [engicos/_companion#1]
Companion is a collection of web apps that helps educational institutions to publicise their information better, improve communication between faculty and students and help users organise their academic planners.

- [ ] Develop an MVP
  - [ ] Basic notice board: This should be easy enough to implement, and will give us data upon which we can build other components
  - [ ] Course view: A core functionality of the app. The basic version won't differ much from the notice board. Just static data that faculty, admins and mods can update.
  - [x] Lecture view: This is designed to be a summary of a physical lecture. can be shifted down priority wise since we won't having those anytime soon.
  - [ ] Discussions between users on events, courses and lectures: A comment section below notices, courses and lectures will improve user engagement
  - [ ] Sign up options for events and courses: We need this to be able to generate data for the timetable
  - [ ] Timetable generated from events, courses user has signed up for: A core functionality, this will help users better organise their academic planners (or do it for them)
- [ ] Host MVP online
- [ ] Review MVP with faculty
